from datetime import datetime

RISK_COLORS = {
    "Critical": "#ff4444",
    "High": "#ff9900",
    "Medium": "#3399ff"
}

def generate(url, status_code, score, findings, info_disclosure):
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    score_color = "#44ff88" if score >= 70 else "#ff9900" if score >= 40 else "#ff4444"

    rows = ""
    for f in findings:
        status_color = "#44ff88" if f["status"] == "PRESENT" else "#ff4444"
        risk_color = RISK_COLORS.get(f["risk"], "#ffffff")
        attack = f["attack"] if f["attack"] else "—"
        rows += f"""
        <tr>
            <td>{f['header']}</td>
            <td style="color:{status_color};font-weight:bold">{f['status']}</td>
            <td style="color:{risk_color};font-weight:bold">{f['risk']}</td>
            <td>{attack}</td>
        </tr>"""

    disclosure_html = ""
    if info_disclosure:
        items = "".join(f"<li>{i}</li>" for i in info_disclosure)
        disclosure_html = f"""
        <div class="disclosure">
            <h3>⚠ Info Disclosure Detected</h3>
            <ul>{items}</ul>
        </div>"""

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>HeaderHawk Report — {url}</title>
<style>
  body {{ font-family: 'Segoe UI', sans-serif; background: #0d1117; color: #e6edf3; margin: 0; padding: 2rem; }}
  h1 {{ color: #58a6ff; font-size: 1.8rem; margin-bottom: 0.2rem; }}
  .meta {{ color: #8b949e; font-size: 13px; margin-bottom: 2rem; }}
  .score {{ font-size: 3rem; font-weight: bold; color: {score_color}; }}
  .score-label {{ color: #8b949e; font-size: 13px; margin-bottom: 2rem; }}
  table {{ width: 100%; border-collapse: collapse; margin-top: 1rem; }}
  th {{ background: #161b22; color: #58a6ff; padding: 10px 14px; text-align: left; font-size: 12px; text-transform: uppercase; letter-spacing: 0.05em; }}
  td {{ padding: 10px 14px; border-bottom: 1px solid #21262d; font-size: 13px; vertical-align: top; }}
  tr:hover {{ background: #161b22; }}
  .disclosure {{ background: #3d1a1a; border: 1px solid #5a2020; border-radius: 8px; padding: 1rem 1.5rem; margin-top: 2rem; }}
  .disclosure h3 {{ color: #ff7b72; margin-bottom: 8px; }}
  .disclosure ul {{ color: #e3b341; padding-left: 1.2rem; font-size: 13px; line-height: 1.8; }}
  .footer {{ margin-top: 3rem; color: #6e7681; font-size: 12px; border-top: 1px solid #21262d; padding-top: 1rem; }}
</style>
</head>
<body>
<h1>🦅 HeaderHawk — Security Report</h1>
<div class="meta">Target: <strong>{url}</strong> &nbsp;|&nbsp; Status: {status_code} &nbsp;|&nbsp; Scanned: {now}</div>
<div class="score">{score}/100</div>
<div class="score-label">Security Score</div>
<table>
  <thead>
    <tr>
      <th>Header</th>
      <th>Status</th>
      <th>Risk</th>
      <th>Attack Scenario</th>
    </tr>
  </thead>
  <tbody>{rows}</tbody>
</table>
{disclosure_html}
<div class="footer">Generated by HeaderHawk — Created by Sachin Singh &nbsp;|&nbsp; github.com/sachinsinsinwar/headerhawk</div>
</body>
</html>"""

    filename = f"headerhawk_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html"
    with open(filename, "w") as f:
        f.write(html)

    return filename
